export const demoStudentData = {
  fullName: 'Arjun Kumar',
  role: 'ST Student',
  mobile: '9999999999',
  state: 'Tamil Nadu',
  district: 'Coimbatore',
  profileCompletion: 92,
  readinessScore: 88,
  bankVerified: true,
  dbtActive: true,
  aadhaarMasked: 'XXXX XXXX 4821',
  bankAccountMasked: '****4521',
  bankName: 'State Bank of India',
  academic: {
    institution: 'Government Arts and Science College, Coimbatore',
    course: 'B.Sc. Computer Science',
    year: '3rd Year (Final)',
    cgpa: 8.4,
  },
  activeApplication: {
    id: 'app-post-matric-1',
    scheme: 'Post-Matric Scholarship for ST Students',
    shortName: 'Post-Matric ST',
    status: 'DEPARTMENT_VERIFICATION',
    stageName: 'Department Verification',
    lastUpdate: 'Application scrutinized and forwarded to District Welfare Officer.',
    daysAgo: '2 days ago',
  },
  nextAction: {
    title: 'Income Certificate Renewal',
    desc: 'Income certificate expires on 15 Nov 2024. Submit renewal application to prevent DBT delay.',
    daysRemaining: 48,
  },
  opportunity: {
    title: 'Top Class Higher Education Scheme',
    desc: 'Your college is recognized under Section 2(f). Check if your department qualifies for enhanced funding.',
  },
  recentPayment: {
    amount: 42000,
    scheme: 'Post-Matric Scholarship',
    cycle: 'Academic Year 2023-2024',
    date: '15 Mar 2024',
    status: 'PAID',
    ref: 'JSS***4124',
  },
  documents: [
    { id: '1', name: 'ST Community Certificate', status: 'VERIFIED', source: 'State e-District Demo', reusable: true },
    { id: '2', name: 'Annual Income Certificate (₹1.8L)', status: 'VERIFIED', source: 'Revenue Dept Demo', reusable: true },
    { id: '3', name: 'Semester Marksheet (82.5%)', status: 'VERIFIED', source: 'APAAR Demo', reusable: true },
    { id: '4', name: 'Aadhaar Identity Card', status: 'VERIFIED', source: 'UIDAI Demo', reusable: true },
    { id: '5', name: 'Bank Account Mandate (SBI)', status: 'VERIFIED', source: 'PFMS / DBT Demo', reusable: true },
    { id: '6', name: 'Nativity / Domicile Certificate', status: 'PENDING', source: 'Demo Integration', reusable: false },
  ],
  schemes: [
    {
      id: 'pre_matric',
      name: 'Pre-Matric Scholarship for ST Students',
      short: 'Pre-Matric ST',
      desc: 'Financial support for ST students enrolled in Classes 9 and 10.',
      amount: '₹3,500 - ₹7,000 / yr',
      status: 'NOT_APPLICABLE',
      statusLabel: 'Completed / College Student',
    },
    {
      id: 'post_matric',
      name: 'Post-Matric Scholarship for ST Students',
      short: 'Post-Matric ST',
      desc: 'Central & State assistance for 11th, 12th, ITI, Degree, and Professional courses.',
      amount: 'Up to ₹45,000 / yr',
      status: 'ACTIVE_APPLICATION',
      statusLabel: 'Under Verification',
    },
    {
      id: 'top_class',
      name: 'National Scholarship for Higher Education (Top Class)',
      short: 'Top Class Education',
      desc: 'Full fee coverage and stipends in notified premier national institutes.',
      amount: 'Up to ₹2,00,000 / yr',
      status: 'LIKELY_ELIGIBLE',
      statusLabel: 'Likely Eligible',
    },
    {
      id: 'nfst',
      name: 'National Fellowship for ST Students (NFST)',
      short: 'NFST Fellowship',
      desc: 'M.Phil and Ph.D. full-time fellowship for ST scholars.',
      amount: '₹28,000 - ₹35,000 / mo',
      status: 'NEEDS_REQUIREMENTS',
      statusLabel: 'For Research Scholars',
    },
    {
      id: 'nos',
      name: 'National Overseas Scholarship (NOS)',
      short: 'National Overseas',
      desc: 'Financial aid for overseas Masters and Ph.D. studies in top foreign universities.',
      amount: 'Up to ₹20,00,000',
      status: 'NOT_ELIGIBLE',
      statusLabel: 'Overseas Studies Only',
    },
  ],
  family: [
    { id: 'f1', name: 'Priya Kumar', relation: 'Sister', scheme: 'Pre-Matric ST', status: 'Disbursed', amount: 3500 },
    { id: 'f2', name: 'Ravi Kumar', relation: 'Brother', scheme: 'Pre-Matric Candidate', status: 'Potential Gap', amount: 0 },
  ],
};
